/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachRouteImport } from './routes/teach'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LevelRouteImport } from './routes/level'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachIndexRouteImport } from './routes/teach.index'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CertificatesIndexRouteImport } from './routes/certificates.index'
import { Route as TeachCourseIdRouteImport } from './routes/teach.$courseId'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as CertificatesCertificateIdRouteImport } from './routes/certificates.$certificateId'
import { Route as AdminTeacherRequestsRouteImport } from './routes/admin.teacher-requests'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as CoursesCourseIdIndexRouteImport } from './routes/courses.$courseId.index'
import { Route as LearnCourseIdLessonIdRouteImport } from './routes/learn.$courseId.$lessonId'
import { Route as CoursesCourseIdResourcesRouteImport } from './routes/courses.$courseId.resources'
import { Route as CoursesCourseIdExamRouteImport } from './routes/courses.$courseId.exam'
import { Route as CertificatesVerifyHashRouteImport } from './routes/certificates.verify.$hash'
import { Route as CoursesCourseIdExamResultRouteImport } from './routes/courses.$courseId.exam.result'

const TeachRoute = TeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelRoute = LevelRouteImport.update({
  id: '/level',
  path: '/level',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachIndexRoute = TeachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeachRoute,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CertificatesIndexRoute = CertificatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CertificatesRoute,
} as any)
const TeachCourseIdRoute = TeachCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => TeachRoute,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => GroupsRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const CertificatesCertificateIdRoute =
  CertificatesCertificateIdRouteImport.update({
    id: '/$certificateId',
    path: '/$certificateId',
    getParentRoute: () => CertificatesRoute,
  } as any)
const AdminTeacherRequestsRoute = AdminTeacherRequestsRouteImport.update({
  id: '/teacher-requests',
  path: '/teacher-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesCourseIdIndexRoute = CoursesCourseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const LearnCourseIdLessonIdRoute = LearnCourseIdLessonIdRouteImport.update({
  id: '/learn/$courseId/$lessonId',
  path: '/learn/$courseId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdResourcesRoute =
  CoursesCourseIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)
const CoursesCourseIdExamRoute = CoursesCourseIdExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const CertificatesVerifyHashRoute = CertificatesVerifyHashRouteImport.update({
  id: '/verify/$hash',
  path: '/verify/$hash',
  getParentRoute: () => CertificatesRoute,
} as any)
const CoursesCourseIdExamResultRoute =
  CoursesCourseIdExamResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => CoursesCourseIdExamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/advisor': typeof AdvisorRoute
  '/approvals': typeof ApprovalsRoute
  '/certificates': typeof CertificatesRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/groups': typeof GroupsRouteWithChildren
  '/level': typeof LevelRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/teach': typeof TeachRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/teacher-requests': typeof AdminTeacherRequestsRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/teach/$courseId': typeof TeachCourseIdRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/teach/': typeof TeachIndexRoute
  '/certificates/verify/$hash': typeof CertificatesVerifyHashRoute
  '/courses/$courseId/exam': typeof CoursesCourseIdExamRouteWithChildren
  '/courses/$courseId/resources': typeof CoursesCourseIdResourcesRoute
  '/learn/$courseId/$lessonId': typeof LearnCourseIdLessonIdRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
  '/courses/$courseId/exam/result': typeof CoursesCourseIdExamResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/advisor': typeof AdvisorRoute
  '/approvals': typeof ApprovalsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/level': typeof LevelRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/teacher-requests': typeof AdminTeacherRequestsRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/teach/$courseId': typeof TeachCourseIdRoute
  '/certificates': typeof CertificatesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/teach': typeof TeachIndexRoute
  '/certificates/verify/$hash': typeof CertificatesVerifyHashRoute
  '/courses/$courseId/exam': typeof CoursesCourseIdExamRouteWithChildren
  '/courses/$courseId/resources': typeof CoursesCourseIdResourcesRoute
  '/learn/$courseId/$lessonId': typeof LearnCourseIdLessonIdRoute
  '/courses/$courseId': typeof CoursesCourseIdIndexRoute
  '/courses/$courseId/exam/result': typeof CoursesCourseIdExamResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/advisor': typeof AdvisorRoute
  '/approvals': typeof ApprovalsRoute
  '/certificates': typeof CertificatesRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/groups': typeof GroupsRouteWithChildren
  '/level': typeof LevelRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/teach': typeof TeachRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/teacher-requests': typeof AdminTeacherRequestsRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/teach/$courseId': typeof TeachCourseIdRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/teach/': typeof TeachIndexRoute
  '/certificates/verify/$hash': typeof CertificatesVerifyHashRoute
  '/courses/$courseId/exam': typeof CoursesCourseIdExamRouteWithChildren
  '/courses/$courseId/resources': typeof CoursesCourseIdResourcesRoute
  '/learn/$courseId/$lessonId': typeof LearnCourseIdLessonIdRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
  '/courses/$courseId/exam/result': typeof CoursesCourseIdExamResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/advisor'
    | '/approvals'
    | '/certificates'
    | '/courses'
    | '/dashboard'
    | '/explore'
    | '/forgot-password'
    | '/groups'
    | '/level'
    | '/login'
    | '/planner'
    | '/profile'
    | '/register'
    | '/teach'
    | '/admin/dashboard'
    | '/admin/teacher-requests'
    | '/certificates/$certificateId'
    | '/courses/$courseId'
    | '/groups/$groupId'
    | '/teach/$courseId'
    | '/certificates/'
    | '/courses/'
    | '/groups/'
    | '/teach/'
    | '/certificates/verify/$hash'
    | '/courses/$courseId/exam'
    | '/courses/$courseId/resources'
    | '/learn/$courseId/$lessonId'
    | '/courses/$courseId/'
    | '/courses/$courseId/exam/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/advisor'
    | '/approvals'
    | '/dashboard'
    | '/explore'
    | '/forgot-password'
    | '/level'
    | '/login'
    | '/planner'
    | '/profile'
    | '/register'
    | '/admin/dashboard'
    | '/admin/teacher-requests'
    | '/certificates/$certificateId'
    | '/groups/$groupId'
    | '/teach/$courseId'
    | '/certificates'
    | '/courses'
    | '/groups'
    | '/teach'
    | '/certificates/verify/$hash'
    | '/courses/$courseId/exam'
    | '/courses/$courseId/resources'
    | '/learn/$courseId/$lessonId'
    | '/courses/$courseId'
    | '/courses/$courseId/exam/result'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/advisor'
    | '/approvals'
    | '/certificates'
    | '/courses'
    | '/dashboard'
    | '/explore'
    | '/forgot-password'
    | '/groups'
    | '/level'
    | '/login'
    | '/planner'
    | '/profile'
    | '/register'
    | '/teach'
    | '/admin/dashboard'
    | '/admin/teacher-requests'
    | '/certificates/$certificateId'
    | '/courses/$courseId'
    | '/groups/$groupId'
    | '/teach/$courseId'
    | '/certificates/'
    | '/courses/'
    | '/groups/'
    | '/teach/'
    | '/certificates/verify/$hash'
    | '/courses/$courseId/exam'
    | '/courses/$courseId/resources'
    | '/learn/$courseId/$lessonId'
    | '/courses/$courseId/'
    | '/courses/$courseId/exam/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvisorRoute: typeof AdvisorRoute
  ApprovalsRoute: typeof ApprovalsRoute
  CertificatesRoute: typeof CertificatesRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  LevelRoute: typeof LevelRoute
  LoginRoute: typeof LoginRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  TeachRoute: typeof TeachRouteWithChildren
  LearnCourseIdLessonIdRoute: typeof LearnCourseIdLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teach': {
      id: '/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof TeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level': {
      id: '/level'
      path: '/level'
      fullPath: '/level'
      preLoaderRoute: typeof LevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach/': {
      id: '/teach/'
      path: '/'
      fullPath: '/teach/'
      preLoaderRoute: typeof TeachIndexRouteImport
      parentRoute: typeof TeachRoute
    }
    '/groups/': {
      id: '/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/certificates/': {
      id: '/certificates/'
      path: '/'
      fullPath: '/certificates/'
      preLoaderRoute: typeof CertificatesIndexRouteImport
      parentRoute: typeof CertificatesRoute
    }
    '/teach/$courseId': {
      id: '/teach/$courseId'
      path: '/$courseId'
      fullPath: '/teach/$courseId'
      preLoaderRoute: typeof TeachCourseIdRouteImport
      parentRoute: typeof TeachRoute
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/certificates/$certificateId': {
      id: '/certificates/$certificateId'
      path: '/$certificateId'
      fullPath: '/certificates/$certificateId'
      preLoaderRoute: typeof CertificatesCertificateIdRouteImport
      parentRoute: typeof CertificatesRoute
    }
    '/admin/teacher-requests': {
      id: '/admin/teacher-requests'
      path: '/teacher-requests'
      fullPath: '/admin/teacher-requests'
      preLoaderRoute: typeof AdminTeacherRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/$courseId/': {
      id: '/courses/$courseId/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof CoursesCourseIdIndexRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/learn/$courseId/$lessonId': {
      id: '/learn/$courseId/$lessonId'
      path: '/learn/$courseId/$lessonId'
      fullPath: '/learn/$courseId/$lessonId'
      preLoaderRoute: typeof LearnCourseIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/resources': {
      id: '/courses/$courseId/resources'
      path: '/resources'
      fullPath: '/courses/$courseId/resources'
      preLoaderRoute: typeof CoursesCourseIdResourcesRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/exam': {
      id: '/courses/$courseId/exam'
      path: '/exam'
      fullPath: '/courses/$courseId/exam'
      preLoaderRoute: typeof CoursesCourseIdExamRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/certificates/verify/$hash': {
      id: '/certificates/verify/$hash'
      path: '/verify/$hash'
      fullPath: '/certificates/verify/$hash'
      preLoaderRoute: typeof CertificatesVerifyHashRouteImport
      parentRoute: typeof CertificatesRoute
    }
    '/courses/$courseId/exam/result': {
      id: '/courses/$courseId/exam/result'
      path: '/result'
      fullPath: '/courses/$courseId/exam/result'
      preLoaderRoute: typeof CoursesCourseIdExamResultRouteImport
      parentRoute: typeof CoursesCourseIdExamRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminTeacherRequestsRoute: typeof AdminTeacherRequestsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminTeacherRequestsRoute: AdminTeacherRequestsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CertificatesRouteChildren {
  CertificatesCertificateIdRoute: typeof CertificatesCertificateIdRoute
  CertificatesIndexRoute: typeof CertificatesIndexRoute
  CertificatesVerifyHashRoute: typeof CertificatesVerifyHashRoute
}

const CertificatesRouteChildren: CertificatesRouteChildren = {
  CertificatesCertificateIdRoute: CertificatesCertificateIdRoute,
  CertificatesIndexRoute: CertificatesIndexRoute,
  CertificatesVerifyHashRoute: CertificatesVerifyHashRoute,
}

const CertificatesRouteWithChildren = CertificatesRoute._addFileChildren(
  CertificatesRouteChildren,
)

interface CoursesCourseIdExamRouteChildren {
  CoursesCourseIdExamResultRoute: typeof CoursesCourseIdExamResultRoute
}

const CoursesCourseIdExamRouteChildren: CoursesCourseIdExamRouteChildren = {
  CoursesCourseIdExamResultRoute: CoursesCourseIdExamResultRoute,
}

const CoursesCourseIdExamRouteWithChildren =
  CoursesCourseIdExamRoute._addFileChildren(CoursesCourseIdExamRouteChildren)

interface CoursesCourseIdRouteChildren {
  CoursesCourseIdExamRoute: typeof CoursesCourseIdExamRouteWithChildren
  CoursesCourseIdResourcesRoute: typeof CoursesCourseIdResourcesRoute
  CoursesCourseIdIndexRoute: typeof CoursesCourseIdIndexRoute
}

const CoursesCourseIdRouteChildren: CoursesCourseIdRouteChildren = {
  CoursesCourseIdExamRoute: CoursesCourseIdExamRouteWithChildren,
  CoursesCourseIdResourcesRoute: CoursesCourseIdResourcesRoute,
  CoursesCourseIdIndexRoute: CoursesCourseIdIndexRoute,
}

const CoursesCourseIdRouteWithChildren = CoursesCourseIdRoute._addFileChildren(
  CoursesCourseIdRouteChildren,
)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRouteWithChildren
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRouteWithChildren,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface GroupsRouteChildren {
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsIndexRoute: GroupsIndexRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

interface TeachRouteChildren {
  TeachCourseIdRoute: typeof TeachCourseIdRoute
  TeachIndexRoute: typeof TeachIndexRoute
}

const TeachRouteChildren: TeachRouteChildren = {
  TeachCourseIdRoute: TeachCourseIdRoute,
  TeachIndexRoute: TeachIndexRoute,
}

const TeachRouteWithChildren = TeachRoute._addFileChildren(TeachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdvisorRoute: AdvisorRoute,
  ApprovalsRoute: ApprovalsRoute,
  CertificatesRoute: CertificatesRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GroupsRoute: GroupsRouteWithChildren,
  LevelRoute: LevelRoute,
  LoginRoute: LoginRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  TeachRoute: TeachRouteWithChildren,
  LearnCourseIdLessonIdRoute: LearnCourseIdLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
