/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LevelRouteImport } from './routes/level'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CertificatesIndexRouteImport } from './routes/certificates.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as CertificatesCertificateIdRouteImport } from './routes/certificates.$certificateId'
import { Route as CoursesCourseIdIndexRouteImport } from './routes/courses.$courseId.index'
import { Route as LearnCourseIdLessonIdRouteImport } from './routes/learn.$courseId.$lessonId'
import { Route as CoursesCourseIdResourcesRouteImport } from './routes/courses.$courseId.resources'
import { Route as CoursesCourseIdExamRouteImport } from './routes/courses.$courseId.exam'
import { Route as CoursesCourseIdExamResultRouteImport } from './routes/courses.$courseId.exam.result'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelRoute = LevelRouteImport.update({
  id: '/level',
  path: '/level',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CertificatesIndexRoute = CertificatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CertificatesRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const CertificatesCertificateIdRoute =
  CertificatesCertificateIdRouteImport.update({
    id: '/$certificateId',
    path: '/$certificateId',
    getParentRoute: () => CertificatesRoute,
  } as any)
const CoursesCourseIdIndexRoute = CoursesCourseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const LearnCourseIdLessonIdRoute = LearnCourseIdLessonIdRouteImport.update({
  id: '/learn/$courseId/$lessonId',
  path: '/learn/$courseId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdResourcesRoute =
  CoursesCourseIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)
const CoursesCourseIdExamRoute = CoursesCourseIdExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const CoursesCourseIdExamResultRoute =
  CoursesCourseIdExamResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => CoursesCourseIdExamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificates': typeof CertificatesRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/level': typeof LevelRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/certificates/': typeof CertificatesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/courses/$courseId/exam': typeof CoursesCourseIdExamRouteWithChildren
  '/courses/$courseId/resources': typeof CoursesCourseIdResourcesRoute
  '/learn/$courseId/$lessonId': typeof LearnCourseIdLessonIdRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
  '/courses/$courseId/exam/result': typeof CoursesCourseIdExamResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/level': typeof LevelRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/certificates': typeof CertificatesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/courses/$courseId/exam': typeof CoursesCourseIdExamRouteWithChildren
  '/courses/$courseId/resources': typeof CoursesCourseIdResourcesRoute
  '/learn/$courseId/$lessonId': typeof LearnCourseIdLessonIdRoute
  '/courses/$courseId': typeof CoursesCourseIdIndexRoute
  '/courses/$courseId/exam/result': typeof CoursesCourseIdExamResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificates': typeof CertificatesRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/level': typeof LevelRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/certificates/': typeof CertificatesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/courses/$courseId/exam': typeof CoursesCourseIdExamRouteWithChildren
  '/courses/$courseId/resources': typeof CoursesCourseIdResourcesRoute
  '/learn/$courseId/$lessonId': typeof LearnCourseIdLessonIdRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
  '/courses/$courseId/exam/result': typeof CoursesCourseIdExamResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificates'
    | '/courses'
    | '/dashboard'
    | '/explore'
    | '/forgot-password'
    | '/level'
    | '/login'
    | '/profile'
    | '/register'
    | '/certificates/$certificateId'
    | '/courses/$courseId'
    | '/certificates/'
    | '/courses/'
    | '/courses/$courseId/exam'
    | '/courses/$courseId/resources'
    | '/learn/$courseId/$lessonId'
    | '/courses/$courseId/'
    | '/courses/$courseId/exam/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/forgot-password'
    | '/level'
    | '/login'
    | '/profile'
    | '/register'
    | '/certificates/$certificateId'
    | '/certificates'
    | '/courses'
    | '/courses/$courseId/exam'
    | '/courses/$courseId/resources'
    | '/learn/$courseId/$lessonId'
    | '/courses/$courseId'
    | '/courses/$courseId/exam/result'
  id:
    | '__root__'
    | '/'
    | '/certificates'
    | '/courses'
    | '/dashboard'
    | '/explore'
    | '/forgot-password'
    | '/level'
    | '/login'
    | '/profile'
    | '/register'
    | '/certificates/$certificateId'
    | '/courses/$courseId'
    | '/certificates/'
    | '/courses/'
    | '/courses/$courseId/exam'
    | '/courses/$courseId/resources'
    | '/learn/$courseId/$lessonId'
    | '/courses/$courseId/'
    | '/courses/$courseId/exam/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificatesRoute: typeof CertificatesRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LevelRoute: typeof LevelRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  LearnCourseIdLessonIdRoute: typeof LearnCourseIdLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level': {
      id: '/level'
      path: '/level'
      fullPath: '/level'
      preLoaderRoute: typeof LevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/certificates/': {
      id: '/certificates/'
      path: '/'
      fullPath: '/certificates/'
      preLoaderRoute: typeof CertificatesIndexRouteImport
      parentRoute: typeof CertificatesRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/certificates/$certificateId': {
      id: '/certificates/$certificateId'
      path: '/$certificateId'
      fullPath: '/certificates/$certificateId'
      preLoaderRoute: typeof CertificatesCertificateIdRouteImport
      parentRoute: typeof CertificatesRoute
    }
    '/courses/$courseId/': {
      id: '/courses/$courseId/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof CoursesCourseIdIndexRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/learn/$courseId/$lessonId': {
      id: '/learn/$courseId/$lessonId'
      path: '/learn/$courseId/$lessonId'
      fullPath: '/learn/$courseId/$lessonId'
      preLoaderRoute: typeof LearnCourseIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/resources': {
      id: '/courses/$courseId/resources'
      path: '/resources'
      fullPath: '/courses/$courseId/resources'
      preLoaderRoute: typeof CoursesCourseIdResourcesRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/exam': {
      id: '/courses/$courseId/exam'
      path: '/exam'
      fullPath: '/courses/$courseId/exam'
      preLoaderRoute: typeof CoursesCourseIdExamRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/exam/result': {
      id: '/courses/$courseId/exam/result'
      path: '/result'
      fullPath: '/courses/$courseId/exam/result'
      preLoaderRoute: typeof CoursesCourseIdExamResultRouteImport
      parentRoute: typeof CoursesCourseIdExamRoute
    }
  }
}

interface CertificatesRouteChildren {
  CertificatesCertificateIdRoute: typeof CertificatesCertificateIdRoute
  CertificatesIndexRoute: typeof CertificatesIndexRoute
}

const CertificatesRouteChildren: CertificatesRouteChildren = {
  CertificatesCertificateIdRoute: CertificatesCertificateIdRoute,
  CertificatesIndexRoute: CertificatesIndexRoute,
}

const CertificatesRouteWithChildren = CertificatesRoute._addFileChildren(
  CertificatesRouteChildren,
)

interface CoursesCourseIdExamRouteChildren {
  CoursesCourseIdExamResultRoute: typeof CoursesCourseIdExamResultRoute
}

const CoursesCourseIdExamRouteChildren: CoursesCourseIdExamRouteChildren = {
  CoursesCourseIdExamResultRoute: CoursesCourseIdExamResultRoute,
}

const CoursesCourseIdExamRouteWithChildren =
  CoursesCourseIdExamRoute._addFileChildren(CoursesCourseIdExamRouteChildren)

interface CoursesCourseIdRouteChildren {
  CoursesCourseIdExamRoute: typeof CoursesCourseIdExamRouteWithChildren
  CoursesCourseIdResourcesRoute: typeof CoursesCourseIdResourcesRoute
  CoursesCourseIdIndexRoute: typeof CoursesCourseIdIndexRoute
}

const CoursesCourseIdRouteChildren: CoursesCourseIdRouteChildren = {
  CoursesCourseIdExamRoute: CoursesCourseIdExamRouteWithChildren,
  CoursesCourseIdResourcesRoute: CoursesCourseIdResourcesRoute,
  CoursesCourseIdIndexRoute: CoursesCourseIdIndexRoute,
}

const CoursesCourseIdRouteWithChildren = CoursesCourseIdRoute._addFileChildren(
  CoursesCourseIdRouteChildren,
)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRouteWithChildren
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRouteWithChildren,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificatesRoute: CertificatesRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LevelRoute: LevelRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  LearnCourseIdLessonIdRoute: LearnCourseIdLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
